cc_binary(
    name = "test_kafka_sender",
    srcs = ["main.cpp"],
    deps = [
        "//impl/cpp:assfire_messenger_cc_impl_kafka",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
    ],
)
