cc_library(
    name = "assfire_messenger_cc_api",
    srcs = [
        "assfire/messenger/api/Api.cpp"
    ],
    hdrs = [
        "assfire/messenger/api/Header.hpp",
        "assfire/messenger/api/Message.hpp",
        "assfire/messenger/api/Payload.hpp",
        "assfire/messenger/api/Publisher.hpp",
        "assfire/messenger/api/Consumer.hpp",
    ],
    include_prefix = "assfire/messenger/api",
    strip_include_prefix = "assfire/messenger/api",
    visibility = ["//visibility:public"]
)
